<a href="https://colab.research.google.com/github/AmeenaSaniya/machine-learning/blob/master/Copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

In [ ]:
!unzip '/content/drive/MyDrive/new/images_training_rev1.zip' -d '/content/drive/MyDrive/new/saniya/train'

In [ ]:
!unzip '/content/drive/MyDrive/new/images_test_rev1.zip' -d '/content/drive/MyDrive/new/saniya/test'

In [ ]:
classes = ['Class1.1', 'Class1.2', 'Class1.3', 'Class2.1', 'Class2.2', 'Class3.1','Class3.2', 'Class4.1', 'Class4.2', 'Class5.1', 'Class5.2', 'Class5.3','Class5.4', 'Class6.1', 'Class6.2', 'Class7.1', 'Class7.2', 'Class7.3','Class8.1', 'Class8.2', 'Class8.3', 'Class8.4', 'Class8.5', 'Class8.6', 'Class8.7', 'Class9.1', 'Class9.2', 'Class9.3', 'Class10.1', 'Class10.2', 'Class10.3', 'Class11.1', 'Class11.2', 'Class11.3', 'Class11.4', 'Class11.5', 'Class11.6'
]

In [ ]:
def append_ext(fn):
    return fn + ".jpg"

In [ ]:
import pandas as pd

In [ ]:
traindf = pd.read_csv('/content/drive/MyDrive/new/training_solutions_rev1.csv')

In [ ]:
traindf

       GalaxyID  Class1.1  Class1.2  ...  Class11.4  Class11.5  Class11.6
0        100008  0.383147  0.616853  ...   0.000000        0.0   0.325512
1        100023  0.327001  0.663777  ...   0.000000        0.0   0.000000
2        100053  0.765717  0.177352  ...   0.000000        0.0   0.000000
3        100078  0.693377  0.238564  ...   0.000000        0.0   0.000000
4        100090  0.933839  0.000000  ...   0.000000        0.0   0.000000
...         ...       ...       ...  ...        ...        ...        ...
61573    999948  0.510379  0.489621  ...   0.000000        0.0   0.226257
61574    999950  0.901216  0.098784  ...   0.000000        0.0   0.000000
61575    999958  0.202841  0.777376  ...   0.000000        0.0   0.072296
61576    999964  0.091000  0.909000  ...   0.023065        0.0   0.045334
61577    999967  0.767000  0.140000  ...   0.000000        0.0   0.023380

[61578 rows x 38 columns]

In [ ]:
traindf["GalaxyID"] = traindf['GalaxyID'].astype(str).apply(append_ext)

In [ ]:
traindf

         GalaxyID  Class1.1  Class1.2  ...  Class11.4  Class11.5  Class11.6
0      100008.jpg  0.383147  0.616853  ...   0.000000        0.0   0.325512
1      100023.jpg  0.327001  0.663777  ...   0.000000        0.0   0.000000
2      100053.jpg  0.765717  0.177352  ...   0.000000        0.0   0.000000
3      100078.jpg  0.693377  0.238564  ...   0.000000        0.0   0.000000
4      100090.jpg  0.933839  0.000000  ...   0.000000        0.0   0.000000
...           ...       ...       ...  ...        ...        ...        ...
61573  999948.jpg  0.510379  0.489621  ...   0.000000        0.0   0.226257
61574  999950.jpg  0.901216  0.098784  ...   0.000000        0.0   0.000000
61575  999958.jpg  0.202841  0.777376  ...   0.000000        0.0   0.072296
61576  999964.jpg  0.091000  0.909000  ...   0.023065        0.0   0.045334
61577  999967.jpg  0.767000  0.140000  ...   0.000000        0.0   0.023380

[61578 rows x 38 columns]

In [ ]:
from keras.preprocessing.image import ImageDataGenerator

In [ ]:
datagen = ImageDataGenerator(
    fill_mode='nearest',
    cval=0,
    rescale=1. / 255,
    rotation_range=90,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    vertical_flip=True,
    validation_split=0.02)

In [ ]:
train_generator = datagen.flow_from_dataframe(
    dataframe=traindf,
    directory="/content/drive/MyDrive/new/saniya/train/images_training_rev1/images_training_rev1",
    x_col="GalaxyID",
    y_col=classes,
    subset="training",
    batch_size=64,
    seed=123,
    shuffle=True,
    class_mode="raw",
    target_size=(224, 224))

Found 60344 validated image filenames.

/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/dataframe_iterator.py:282: UserWarning: Found 3 invalid image filename(s) in x_col="GalaxyID". These filename(s) will be ignored.
  .format(n_invalid, x_col)

In [ ]:
valid_generator = datagen.flow_from_dataframe(
    dataframe=traindf,
    directory="/content/drive/MyDrive/new/saniya/train/images_training_rev1/images_training_rev1",
    x_col="GalaxyID",
    y_col=classes,
    subset="validation",
    batch_size=64,
    seed=123,
    shuffle=True,
    class_mode="raw",
    target_size=(224, 224))

Found 1231 validated image filenames.

In [ ]:
train_size = train_generator.n // train_generator.batch_size
valid_size = valid_generator.n // valid_generator.batch_size

In [ ]:
train_size,valid_size

(942, 19)

In [ ]:
import keras
print(dir(keras.applications))

['DenseNet121', 'DenseNet169', 'DenseNet201', 'InceptionResNetV2', 'InceptionV3', 'MobileNet', 'MobileNetV2', 'NASNetLarge', 'NASNetMobile', 'ResNet101', 'ResNet101V2', 'ResNet152', 'ResNet152V2', 'ResNet50', 'ResNet50V2', 'VGG16', 'VGG19', 'Xception', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'densenet', 'inception_resnet_v2', 'inception_v3', 'mobilenet', 'mobilenet_v2', 'nasnet', 'resnet', 'resnet50', 'resnet_v2', 'vgg16', 'vgg19', 'xception']

In [ ]:
from keras.applications.vgg16 import VGG16, preprocess_input
from keras.preprocessing.image import load_img,img_to_array
from keras.models import Model
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
img_shape = (224, 224, 3)
vgg_model = VGG16(include_top=False, input_shape=img_shape)

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5
58892288/58889256 [==============================] - 0s 0us/step

In [ ]:
# Flatten output of last layer before adding output layer (Dense layer)
from keras.layers.core import Flatten, Dense, Dropout, Lambda, Reshape
x = Flatten()(vgg_model.output)
# Add output layer (number of outputs = 37)
x = Dense(len(classes), activation='sigmoid')(x)
# Load the modified model
model = Model(inputs=vgg_model.input, outputs=x)

In [ ]:
for layer in model.layers:
    layer.trainable = True

In [ ]:
optimizer = keras.optimizers.Adam(lr=0.001, decay=5e-4)
model.compile(optimizer, loss='mse', metrics=["accuracy"])
from keras.callbacks import Callback
from keras.callbacks import ModelCheckpoint, Callback, EarlyStopping

In [ ]:
from keras.callbacks import ModelCheckpoint
checkpointer = ModelCheckpoint(
    filepath='today_20_epochs/weights.hdf5', verbose=2, save_best_only=True)

In [ ]:
hist = model.fit_generator(
    train_generator,
    steps_per_epoch=train_size,
    validation_data=valid_generator,
    validation_steps=valid_size,
    epochs=15,
    #callbacks=[history, checkpointer, early_stopping])
    callbacks=[checkpointer])

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '

Epoch 1/12
942/942 [==============================] - 17704s 19s/step - loss: 0.0613 - accuracy: 0.2544 - val_loss: 0.0596 - val_accuracy: 0.2401

Epoch 00001: val_loss improved from inf to 0.05957, saving model to today_20_epochs/weights.hdf5
Epoch 2/12
942/942 [==============================] - 1059s 1s/step - loss: 0.0604 - accuracy: 0.2614 - val_loss: 0.0595 - val_accuracy: 0.2385

Epoch 00002: val_loss improved from 0.05957 to 0.05953, saving model to today_20_epochs/weights.hdf5
Epoch 3/12
942/942 [==============================] - ETA: 0s - loss: 0.0603 - accuracy: 0.2586